/* eslint-disable @next/next/no-page-custom-font */
import Navbar from "@/common/Navbar";

import { ReduxProvider } from "@/utils/ReduxProvider";

import "./globals.css";
import Footer from "@/common/Footer";

export const metadata = {
  title: "StellaNex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark scroll-smooth">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
        />
      </head>
      <body className="overflow-x-hidden">
        <ReduxProvider>
          <header className="w-dvw sticky top-0 z-50">
            <Navbar />
          </header>
          <main className="flex flex-col scroll-smooth pointer-events-auto bg-slate-950">
            {children}
          </main>
          <footer className="w-dvw bg-slate-950 flex justify-center items-center">
            <Footer />
          </footer>
        </ReduxProvider>
      </body>
    </html>
  );
}
